// AI Labs
export const AI_LABS = [
  { id: 'openai', name: 'OpenAI', icon: '🧠', color: '#10A37F' },
  { id: 'anthropic', name: 'Anthropic', icon: '👑', color: '#C8622A' },
  { id: 'google', name: 'Google DeepMind', icon: '🔬', color: '#4285F4' },
  { id: 'meta', name: 'Meta', icon: '🦙', color: '#0668E1' },
  { id: 'deepseek', name: 'DeepSeek', icon: '💻', color: '#4B6BFB' },
  { id: 'alibaba', name: 'Alibaba (Qwen)', icon: '🀄', color: '#FF6B6B' },
  { id: 'xai', name: 'xAI', icon: '𝕏', color: '#1DA1F2' },
  { id: 'mistral', name: 'Mistral AI', icon: '🌀', color: '#FF7000' },
  { id: 'nvidia', name: 'NVIDIA NIM', icon: '🟢', color: '#76B900' },
  { id: 'cohere', name: 'Cohere', icon: '🔵', color: '#39594D' },
  { id: 'microsoft', name: 'Microsoft', icon: '🪟', color: '#00A4EF' },
  { id: 'amazon', name: 'Amazon', icon: '📦', color: '#FF9900' },
  { id: 'baidu', name: 'Baidu', icon: '🔴', color: '#DE2910' },
  { id: 'zhipu', name: 'Zhipu AI', icon: '🔷', color: '#00BCD4' },
  { id: 'moonshot', name: 'Moonshot AI', icon: '🌙', color: '#6C63FF' },
  { id: 'ai21', name: 'AI21 Labs', icon: '🟣', color: '#4CAF50' },
  { id: 'perplexity', name: 'Perplexity AI', icon: '🔍', color: '#20808D' },
  { id: 'inflection', name: 'Inflection AI', icon: '💜', color: '#FFC107' },
  { id: 'allenai', name: 'Allen AI', icon: '🏛', color: '#795548' },
  { id: 'stability', name: 'Stability AI', icon: '🎨', color: '#7B68EE' },
  { id: 'google-open', name: 'Google (Open)', icon: '💎', color: '#4285F4' },
  { id: 'databricks', name: 'Databricks', icon: '🧱', color: '#FF5722' },
  { id: 'ibm', name: 'IBM', icon: '🔵', color: '#054ADA' },
  { id: 'tii', name: 'Technology Innovation Institute', icon: '🦅', color: '#8B6914' },
  { id: 'eleutherai', name: 'EleutherAI', icon: '⚡', color: '#607D8B' },
  { id: 'bigscience', name: 'BigScience', icon: '🌍', color: '#4CAF50' },
  { id: 'minimax', name: 'MiniMax', icon: '🟡', color: '#FF9800' },
  { id: 'tencent', name: 'Tencent', icon: '🐧', color: '#07C160' },
  { id: 'huggingface', name: 'HuggingFace', icon: '🤗', color: '#FFD21E' },
  { id: 'cerebras', name: 'Cerebras', icon: '🧠', color: '#E91E63' },
  { id: 'writer', name: 'Writer', icon: '✍️', color: '#795548' },
];

// Featured Models (9 cards matching reference)
export const FEATURED_MODELS = [
  {
    id: 'gpt-5',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'OpenAI flagship. Native computer-use agents, advanced reasoning, 2M context.',
    tags: ['Flagship', 'Agents', 'Multimodal'],
    badge: 'hot' as const,
    rating: 4.9,
    reviews: 4210,
    price: '$7.50/1M tk',
    priceStart: 7.5,
    types: ['language', 'vision', 'code'],
  },
  {
    id: 'gpt-5.2',
    icon: '🧠',
    bg: '#EBF0FC',
    name: 'GPT-5.2',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Mid-tier GPT-5 variant with improved instruction-following and multimodal support.',
    tags: ['Multimodal', 'Balanced', 'Instruction'],
    badge: 'new' as const,
    rating: 4.8,
    reviews: 2180,
    price: '$4/1M tk',
    priceStart: 4,
    types: ['language', 'vision'],
  },
  {
    id: 'gpt-5-turbo',
    icon: '⚡',
    bg: '#FFF3E8',
    name: 'GPT-5 Turbo',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Fast, cost-effective GPT-5 for high-volume deployments.',
    tags: ['Fast', 'Cost-Effective', 'High-Volume'],
    badge: 'hot' as const,
    rating: 4.8,
    reviews: 3560,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language', 'code'],
  },
  {
    id: 'gpt-4.5',
    icon: '🔮',
    bg: '#F3E8FF',
    name: 'GPT-4.5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Bridging model with improved creativity and long-form generation.',
    tags: ['Creative', 'Long-form', 'Language'],
    rating: 4.7,
    reviews: 1980,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'gpt-4.1',
    icon: '💡',
    bg: '#E2F5EF',
    name: 'GPT-4.1',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Optimized for coding and instruction-following with 128K context.',
    tags: ['Code', 'Instructions', '128K'],
    rating: 4.7,
    reviews: 2310,
    price: '$2/1M tk',
    priceStart: 2,
    types: ['language', 'code'],
  },
  {
    id: 'gpt-4.1-mini',
    icon: '⚡',
    bg: '#FFF3E8',
    name: 'GPT-4.1-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Lightweight GPT-4.1 for fast, affordable everyday tasks.',
    tags: ['Fast', 'Affordable', 'Everyday'],
    rating: 4.5,
    reviews: 1870,
    price: '$0.40/1M tk',
    priceStart: 0.4,
    types: ['language'],
  },
  {
    id: 'gpt-4o',
    icon: '🌟',
    bg: '#D7F5EC',
    name: 'GPT-4o',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Multimodal flagship combining text, vision, and audio in one unified model.',
    tags: ['Multimodal', 'Vision', 'Audio'],
    rating: 4.7,
    reviews: 5120,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language', 'vision', 'audio'],
  },
  {
    id: 'gpt-4o-mini',
    icon: '🔹',
    bg: '#EBF0FC',
    name: 'GPT-4o-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Affordable, fast GPT-4o for lightweight chat and classification tasks.',
    tags: ['Fast', 'Budget', 'Chat'],
    rating: 4.5,
    reviews: 4380,
    price: '$0.15/1M tk',
    priceStart: 0.15,
    types: ['language'],
  },
  {
    id: 'o3',
    icon: '🧩',
    bg: '#FDEDF1',
    name: 'o3',
    lab: 'openai',
    org: 'OpenAI',
    desc: "OpenAI's advanced reasoning model with chain-of-thought for complex tasks.",
    tags: ['Reasoning', 'Math', 'Science'],
    badge: 'hot' as const,
    rating: 4.8,
    reviews: 1640,
    price: '$15/1M tk',
    priceStart: 15,
    types: ['language', 'code'],
  },
];

// Flagship comparison models (14 models matching reference)
export type SpeedType = 'fastest' | 'fast' | 'moderate' | 'slow';

export interface FlagshipModel {
  name: string;
  org: string;
  lab: string;
  icon: string;
  context: string;
  inputPrice: string;
  outputPrice: string;
  speed: SpeedType;
  multimodal: boolean;
  bestFor: string;
  badge: string | null;
}

export const FLAGSHIP_MODELS: FlagshipModel[] = [
  { name: 'GPT-5.4', org: 'OpenAI', lab: 'OpenAI', icon: '🧠', context: '1.05M', inputPrice: '$2.50', outputPrice: '$15', speed: 'fast', multimodal: true, bestFor: 'High-precision professional tasks', badge: null },
  { name: 'Claude Opus 4.6', org: 'Anthropic', lab: 'Anthropic', icon: '👑', context: '200K/1M β', inputPrice: '$5', outputPrice: '$25', speed: 'moderate', multimodal: true, bestFor: 'Agents, advanced coding', badge: 'hot' },
  { name: 'Claude Sonnet 4.6', org: 'Anthropic', lab: 'Anthropic', icon: '⚡', context: '200K/1M β', inputPrice: '$3', outputPrice: '$15', speed: 'fast', multimodal: true, bestFor: 'Code, data, content at scale', badge: 'new' },
  { name: 'Claude Haiku 4.5', org: 'Anthropic', lab: 'Anthropic', icon: '🚀', context: '200K', inputPrice: '$1', outputPrice: '$5', speed: 'fastest', multimodal: true, bestFor: 'Real-time, high-volume', badge: null },
  { name: 'Gemini 3.1 Pro', org: 'Google', lab: 'Google DeepMind', icon: '🔬', context: '2M–5M', inputPrice: '$2', outputPrice: '$12', speed: 'moderate', multimodal: true, bestFor: 'Deep reasoning, long context', badge: 'new' },
  { name: 'Gemini 3 Flash', org: 'Google', lab: 'Google DeepMind', icon: '⚡', context: '1M', inputPrice: '$2', outputPrice: '$12', speed: 'moderate', multimodal: true, bestFor: 'High-volume chat & coding', badge: null },
  { name: 'Gemini 3.1 Flash-Lite', org: 'Google', lab: 'Google DeepMind', icon: '💡', context: '1M', inputPrice: '$0.10', outputPrice: '$0.40', speed: 'fastest', multimodal: true, bestFor: 'Low-cost agents, translation', badge: null },
  { name: 'Grok-4-1 Fast', org: 'xAI', lab: 'xAI', icon: '𝕏', context: '2000K', inputPrice: '$0.20', outputPrice: '$0.50', speed: 'moderate', multimodal: true, bestFor: 'Real-time X data analysis', badge: null },
  { name: 'DeepSeek-V3', org: 'DeepSeek', lab: 'DeepSeek', icon: '💻', context: '128K', inputPrice: '~$0.07', outputPrice: '~$0.28', speed: 'moderate', multimodal: true, bestFor: 'Budget general model', badge: 'open' },
  { name: 'Llama 4 Maverick', org: 'Meta', lab: 'Meta', icon: '🦙', context: '128K', inputPrice: 'Free', outputPrice: 'Free', speed: 'moderate', multimodal: true, bestFor: 'Open-source multimodal', badge: 'open' },
  { name: 'Qwen3-Max', org: 'Alibaba', lab: 'Alibaba', icon: '🀄', context: '128K', inputPrice: '$0.40', outputPrice: '$1.20', speed: 'moderate', multimodal: true, bestFor: 'Multilingual / APAC', badge: null },
  { name: 'Devstral 2', org: 'Mistral', lab: 'Mistral', icon: '🌀', context: '256K', inputPrice: '$0.40', outputPrice: '$2', speed: 'fastest', multimodal: true, bestFor: 'Software engineering agents', badge: null },
  { name: 'Nemotron Ultra 253B', org: 'NVIDIA', lab: 'NVIDIA', icon: '🟢', context: '131K', inputPrice: '$0.60', outputPrice: '$1.80', speed: 'moderate', multimodal: false, bestFor: 'Enterprise reasoning & RAG', badge: null },
  { name: 'kimi-k2.5', org: 'Moonshot', lab: 'Moonshot', icon: '🌙', context: '262K', inputPrice: '$0.60', outputPrice: '$3', speed: 'fastest', multimodal: true, bestFor: 'Multi-agent RAG, visual coding', badge: null },
];

// Trending models (6 cards matching reference)
export const TRENDING_MODELS = [
  {
    id: 'claude-opus-sonnet-4.6',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Opus 4.6 & Sonnet 4.6',
    org: 'Anthropic',
    desc: 'Adaptive Thinking and 1M token context (beta) mark a major leap in agent capability. Now the most intelligent Claude for coding and agentic tasks.',
    badge: 'Just Released',
    badgeColor: '#9B2042',
    rating: 4.9,
    price: '$3–$5/1M tk',
  },
  {
    id: 'gemini-3.1-pro',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 3.1 Pro — Thought Signatures',
    org: 'Google DeepMind',
    desc: 'Thought Signatures bring new transparency to deep reasoning. 5M context window makes it the go-to for ultra-long document analysis.',
    badge: 'Hot',
    badgeColor: '#FF4757',
    rating: 4.7,
    price: '$2/1M tk',
  },
  {
    id: 'gpt-5.4',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5.4 — Native Computer-Use Agents',
    org: 'OpenAI',
    desc: "GPT-5.4 introduces native computer-use agents, letting it operate browsers, apps, and files autonomously with improved reasoning efficiency.",
    badge: 'Computer Use',
    badgeColor: '#1E4DA8',
    rating: 4.8,
    price: '$2.50/1M tk',
  },
  {
    id: 'grok-4-1',
    icon: '𝕏',
    bg: '#F0F0F0',
    name: 'Grok-4-1 Fast — 4-Agent Architecture',
    org: 'xAI',
    desc: "Grok's 4-agent architecture with real-time X (Twitter) data access and 2M context makes it unique for real-time analysis tasks.",
    badge: 'Real-Time',
    badgeColor: '#0A5E49',
    rating: 4.5,
    price: '$0.20/1M tk',
  },
  {
    id: 'llama-4-maverick',
    icon: '🦙',
    bg: '#E2F5EF',
    name: 'Llama 4 Maverick — 400B MoE',
    org: 'Meta',
    desc: "Meta's 400B Mixture-of-Experts model with native multimodal understanding. Free to self-host with a full commercial licence.",
    badge: 'Open Source',
    badgeColor: '#0668E1',
    rating: 4.6,
    price: 'Free (self-host)',
  },
  {
    id: 'devstral-2',
    icon: '🌀',
    bg: '#FFF3E8',
    name: 'Devstral 2 — Fastest Coding Agent',
    org: 'Mistral',
    desc: "Mistral's coding agent with 256K context, multi-file edits, and codebase navigation. The fastest software engineering model available.",
    badge: 'Coding',
    badgeColor: '#FF7000',
    rating: 4.5,
    price: '$0.40/1M tk',
  },
];

// Budget tiers (matching reference with model counts)
export const BUDGET_TIERS = [
  {
    icon: '🆓',
    label: 'Free & Open Source',
    desc: 'Self-host with zero API cost.',
    color: '#0A5E49',
    bg: '#E2F5EF',
    modelCount: 6,
    models: ['Llama 4 Maverick', 'Llama 4 Scout', 'DeepSeek-V3', 'DeepSeek-R1'],
  },
  {
    icon: '💸',
    label: 'Budget — Under $0.50/1M',
    desc: 'Best performance per dollar.',
    color: '#1E4DA8',
    bg: '#EBF0FC',
    modelCount: 9,
    models: ['Gemini 3.1 Flash-Lite', 'Mistral Medium', 'Nemotron Nano'],
  },
  {
    icon: '⚖️',
    label: 'Mid-Range — $1–$5/1M',
    desc: 'Professional quality at scale.',
    color: '#8A5A00',
    bg: '#FDF5E0',
    modelCount: 11,
    models: ['Claude Sonnet 4.6', 'Claude Haiku 4.5', 'Gemini 3.1 Pro', 'GPT-5.4', 'Qwen3-Max'],
  },
  {
    icon: '🏆',
    label: 'Premium — $5+/1M',
    desc: 'Top-tier quality for demanding workloads.',
    color: '#9B2042',
    bg: '#FDEDF1',
    modelCount: 5,
    models: ['Claude Opus 4.6', 'Sora 2 Pro', 'gpt-image-1.5'],
  },
];

// Use cases (matching reference)
export const USE_CASES = [
  { icon: '💻', label: 'Code Generation', models: ['Claude Opus 4.6', 'Devstral 2', 'GPT-5.4', 'Qwen3-Coder'], actionLabel: 'Start building' },
  { icon: '🎨', label: 'Image Generation', models: ['gpt-image-1.5', 'Grok-Imagine-Pro', 'Gemini Flash Image'], actionLabel: 'Create images' },
  { icon: '🤖', label: 'AI Agents', models: ['GPT-5.4', 'Claude Opus 4.6', 'kimi-k2.5', 'Grok-4-1'], actionLabel: 'Build agents' },
  { icon: '📄', label: 'Document Analysis', models: ['Claude Sonnet 4.6', 'Gemini 3.1 Pro', 'Nemotron Ultra'], actionLabel: 'Analyse docs' },
  { icon: '🎬', label: 'Video Generation', models: ['Sora 2 Pro', 'Veo 3.1', 'Grok-Imagine-Video'], actionLabel: 'Create video' },
  { icon: '🔊', label: 'Voice & Audio', models: ['Gemini-TTS', 'ElevenLabs', 'Whisper v3'], actionLabel: 'Add voice' },
  { icon: '🌍', label: 'Multilingual / Translation', models: ['Qwen3-Max (119 langs)', 'Gemini 3.1 Flash-Lite', 'GLM-4.7'], actionLabel: 'Go multilingual' },
  { icon: '🔢', label: 'Math & Research', models: ['DeepSeek-R1', 'QwQ-32B', 'Gemini 3.1 Pro'], actionLabel: 'Start researching' },
];

// Feature cards for "Built for every builder" (matching reference)
export const BUILDER_FEATURES = [
  {
    icon: '🧭',
    title: 'Guided Discovery Chat',
    desc: "I'll greet you, ask about your goals, and have a genuine conversation before recommending models. No overwhelming lists.",
  },
  {
    icon: '📐',
    title: 'Prompt Engineering Guide',
    desc: 'Every model includes tailored prompt templates, principles, and examples so you get the best output from day one.',
  },
  {
    icon: '🤖',
    title: 'Agent Builder',
    desc: 'Step-by-step agent creation guides for every model — system prompts, tool configuration, memory setup, deployment.',
  },
  {
    icon: '💰',
    title: 'Flexible Pricing',
    desc: 'Free tiers, pay-per-use, subscriptions, and enterprise plans. Transparent pricing with no hidden fees.',
  },
  {
    icon: '⭐',
    title: 'User Reviews & Ratings',
    desc: 'Verified reviews from real builders, benchmark scores, and detailed I/O specs to help you choose confidently.',
  },
  {
    icon: '🔬',
    title: 'Research Feed',
    desc: 'Daily curated AI research, model releases, and breakthroughs from top labs — stay ahead of the curve.',
  },
];

// Browse by AI Lab data (11 labs matching reference)
export const BROWSE_BY_LAB_DATA = [
  { id: 'openai', name: 'OpenAI', icon: '🧠', color: '#10A37F', modelCount: 3, upcoming: 'GPT-5.4, Sora 2' },
  { id: 'anthropic', name: 'Anthropic', icon: '⚡', color: '#C8622A', modelCount: 3, upcoming: 'Opus, Sonnet, Haiku' },
  { id: 'google', name: 'Google DeepMind', icon: '🔬', color: '#4285F4', modelCount: 5, upcoming: 'Gemini 3.1, Veo 3' },
  { id: 'xai', name: 'xAI (Grok)', icon: '𝕏', color: '#1DA1F2', modelCount: 2, upcoming: 'Grok-4-1, Grok-Imagine' },
  { id: 'deepseek', name: 'DeepSeek', icon: '💻', color: '#4B6BFB', modelCount: 3, upcoming: 'V3, V3.2, R1' },
  { id: 'meta', name: 'Meta (Llama)', icon: '🦙', color: '#0668E1', modelCount: 2, upcoming: 'Maverick, Scout' },
  { id: 'alibaba', name: 'Alibaba (Qwen)', icon: '🀄', color: '#FF6B6B', modelCount: 2, upcoming: 'Qwen3-Max, Coder' },
  { id: 'mistral', name: 'Mistral', icon: '🌀', color: '#FF7000', modelCount: 2, upcoming: 'Devstral 2, Medium 3.1' },
  { id: 'nvidia', name: 'NVIDIA NIM', icon: '🟢', color: '#76B900', modelCount: 4, upcoming: 'Nemotron Ultra, Nano' },
  { id: 'zhipu', name: 'GLM (Zhipu)', icon: '🔷', color: '#00BCD4', modelCount: 3, upcoming: 'GLM-5, 4.7, 4.6V' },
  { id: 'moonshot', name: 'Moonshot (Kimi)', icon: '🌙', color: '#6C63FF', modelCount: 2, upcoming: 'k2.5, k2-Thinking' },
];

// Footer model catalog (grouped by lab, matching reference)
export const FOOTER_MODEL_CATALOG: Record<string, { icon: string; models: string[] }> = {
  'OpenAI': { icon: '🧠', models: ['GPT-5', 'GPT-5.2', 'GPT-5 Turbo', 'GPT-4.5', 'GPT-4.1', 'GPT-4.1-mini', 'GPT-4o', 'GPT-4o-mini', 'o3', 'o3-mini', 'o4-mini'] },
  'Anthropic': { icon: '👑', models: ['Claude Opus 4.6', 'Claude Opus 4.5', 'Claude Opus 4', 'Claude Sonnet 4.6', 'Claude Sonnet 4.5', 'Claude Sonnet 4', 'Claude Haiku 4.5', 'Claude Haiku 4'] },
  'Google DeepMind': { icon: '🔬', models: ['Gemini 3.1 Pro', 'Gemini 3 Pro', 'Gemini 3 Flash', 'Gemini 2.5 Pro', 'Gemini 2.5 Flash', 'Gemini 2.0 Flash', 'Gemini 1.5 Pro', 'Gemini 1.5 Flash'] },
  'Meta': { icon: '🦙', models: ['Llama 4 Maverick', 'Llama 4 Scout', 'Llama 3.3 70B', 'Llama 3.1 405B', 'Llama 3.1 70B', 'Llama 3 70B', 'Llama 3 8B', 'Llama 2'] },
  'DeepSeek': { icon: '💻', models: ['DeepSeek-R1', 'DeepSeek-R1-Zero', 'DeepSeek-V3', 'DeepSeek-V3.2', 'DeepSeek-V2.5', 'DeepSeek Coder V2'] },
  'Alibaba (Qwen)': { icon: '🀄', models: ['Qwen3-Max', 'Qwen3', 'Qwen3-32B', 'Qwen2.5-Max', 'Qwen2.5-72B', 'Qwen2.5-Coder', 'Qwen-VL', 'Qwen-Omni', 'QwQ-32B'] },
  'xAI': { icon: '𝕏', models: ['Grok-4', 'Grok-4 Fast', 'Grok-3', 'Grok-2', 'Grok-1.5', 'Grok-1'] },
  'Mistral AI': { icon: '🌀', models: ['Mistral Large 3', 'Mistral Large 2', 'Mistral Medium', 'Mistral Small', 'Mixtral 8x22B', 'Mixtral 8x7B', 'Codestral', 'Mistral 7B'] },
  'Cohere': { icon: '🔵', models: ['Command A', 'Command R+', 'Command R', 'Command Light', 'Aya'] },
  'Microsoft': { icon: '🪟', models: ['Phi-4', 'Phi-4 Reasoning', 'Phi-3 Medium', 'Phi-3 Small', 'Phi-3 Mini', 'Phi-2'] },
  'Amazon': { icon: '📦', models: ['Nova Premier', 'Nova Pro', 'Nova Lite', 'Titan Text', 'Titan Multimodal'] },
  'Baidu': { icon: '🔴', models: ['ERNIE 5.0', 'ERNIE 4.5', 'ERNIE 4', 'ERNIE Bot'] },
  'Zhipu AI': { icon: '🔷', models: ['GLM-5', 'GLM-4.7', 'GLM-4.6', 'GLM-4', 'CodeGeeX'] },
  'Moonshot AI': { icon: '🌙', models: ['Kimi K2.5', 'Kimi K2', 'Kimi K1.5'] },
  'AI21 Labs': { icon: '🟣', models: ['Jamba Large', 'Jamba Instruct', 'Jurassic-2 Ultra', 'Jurassic-2 Mid'] },
  'NVIDIA': { icon: '🟢', models: ['Nemotron Ultra 253B', 'Nemotron-4', 'Nemotron-3'] },
  'Perplexity AI': { icon: '🔍', models: ['Sonar Large', 'Sonar Medium', 'Sonar Reasoning', 'Sonar Small'] },
  'Inflection AI': { icon: '💜', models: ['Inflection-3', 'Inflection-2.5', 'Pi'] },
  'Allen AI': { icon: '🏛', models: ['OLMo-3', 'OLMo-2', 'OLMo-1'] },
  'Stability AI': { icon: '🎨', models: ['StableLM 3', 'StableLM 2', 'StableLM Zephyr'] },
  'Google (Open)': { icon: '💎', models: ['Gemma 3', 'Gemma 2', 'Gemma 7B', 'Gemma 2B'] },
  'Databricks': { icon: '🧱', models: ['DBRX', 'DBRX-Instruct'] },
  'IBM': { icon: '🔵', models: ['Granite 20B', 'Granite 13B', 'Granite Code'] },
  'Technology Innovation Institute': { icon: '🦅', models: ['Falcon 180B', 'Falcon 40B', 'Falcon 7B'] },
  'EleutherAI': { icon: '⚡', models: ['Pythia 12B', 'Pythia 6.9B', 'Pythia 2.8B'] },
  'BigScience': { icon: '🌍', models: ['BLOOM', 'BLOOMZ'] },
  'MiniMax': { icon: '🟡', models: ['MiniMax-M2.5', 'MiniMax-M1'] },
  'Tencent': { icon: '🐧', models: ['Hunyuan Large', 'Hunyuan Turbo'] },
  'HuggingFace': { icon: '🤗', models: ['H4-Zephyr', 'H4-OpenChat'] },
  'Cerebras': { icon: '🧠', models: ['Cerebras-GPT-111M', 'Cerebras-GPT-13B'] },
  'Writer': { icon: '✍️', models: ['Palmyra Large', 'Palmyra Small'] },
};
