// AI Labs
export const AI_LABS = [
  { id: 'openai', name: 'OpenAI', icon: '🧠', color: '#10A37F' },
  { id: 'anthropic', name: 'Anthropic', icon: '👑', color: '#C8622A' },
  { id: 'google', name: 'Google DeepMind', icon: '🔬', color: '#4285F4' },
  { id: 'meta', name: 'Meta AI', icon: '🌐', color: '#0668E1' },
  { id: 'mistral', name: 'Mistral AI', icon: '💨', color: '#FF7000' },
  { id: 'cohere', name: 'Cohere', icon: '🔗', color: '#39594D' },
  { id: 'nvidia', name: 'NVIDIA', icon: '⚡', color: '#76B900' },
  { id: 'deepseek', name: 'DeepSeek', icon: '🔍', color: '#4B6BFB' },
  { id: 'qwen', name: 'Qwen', icon: '🌸', color: '#FF6B6B' },
  { id: 'microsoft', name: 'Microsoft', icon: '🪟', color: '#00A4EF' },
  { id: 'amazon', name: 'Amazon Bedrock', icon: '📦', color: '#FF9900' },
  { id: 'xai', name: 'xAI', icon: '✖️', color: '#1DA1F2' },
  { id: 'stability', name: 'Stability AI', icon: '🎨', color: '#7B68EE' },
  { id: 'perplexity', name: 'Perplexity', icon: '🔎', color: '#20808D' },
  { id: 'together', name: 'Together AI', icon: '🤝', color: '#6C63FF' },
];

// Featured Models
export const FEATURED_MODELS = [
  {
    id: 'gpt-4.1',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.1',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Flagship model with 1M context window and superior coding performance.',
    tags: ['Language', 'Vision', 'Code'],
    badge: 'hot' as const,
    rating: 4.9,
    reviews: 2847,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language', 'vision', 'code'],
  },
  {
    id: 'claude-opus-4',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Opus 4',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Most intelligent model for complex reasoning and nuanced understanding.',
    tags: ['Language', 'Analysis', 'Code'],
    badge: 'new' as const,
    rating: 4.8,
    reviews: 1923,
    price: '$15.00/1M tk',
    priceStart: 15,
    types: ['language', 'code'],
  },
  {
    id: 'gemini-2.0-flash',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 2.0 Flash',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Ultra-fast multimodal model with real-time streaming and tool use.',
    tags: ['Language', 'Vision', 'Audio'],
    rating: 4.7,
    reviews: 1456,
    price: '$0.10/1M tk',
    priceStart: 0.1,
    types: ['language', 'vision', 'audio'],
  },
  {
    id: 'llama-4-scout',
    icon: '🌐',
    bg: '#E2F5EF',
    name: 'Llama 4 Scout',
    lab: 'meta',
    org: 'Meta AI',
    desc: 'Open-source multimodal model with 10M context and 17B parameters.',
    tags: ['Language', 'Open Source'],
    badge: 'open' as const,
    rating: 4.6,
    reviews: 987,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },
  {
    id: 'mistral-large-3',
    icon: '💨',
    bg: '#FFF3E8',
    name: 'Mistral Large 3',
    lab: 'mistral',
    org: 'Mistral AI',
    desc: 'Top-tier reasoning with multilingual support and function calling.',
    tags: ['Language', 'Code', 'Multilingual'],
    rating: 4.5,
    reviews: 743,
    price: '$3.00/1M tk',
    priceStart: 3,
    types: ['language', 'code'],
  },
  {
    id: 'deepseek-v3',
    icon: '🔍',
    bg: '#EBF0FC',
    name: 'DeepSeek V3',
    lab: 'deepseek',
    org: 'DeepSeek',
    desc: 'Cost-efficient frontier model with exceptional math and coding.',
    tags: ['Language', 'Code', 'Open Source'],
    badge: 'open' as const,
    rating: 4.7,
    reviews: 1204,
    price: '$0.14/1M tk',
    priceStart: 0.14,
    types: ['language', 'code', 'open'],
  },
];

// Flagship comparison models
export const FLAGSHIP_MODELS = [
  { name: 'GPT-4.1', org: 'OpenAI', icon: '🧠', context: '1M', price: '$2.50', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'hot' },
  { name: 'GPT-4.1 Mini', org: 'OpenAI', icon: '🧠', context: '1M', price: '$0.40', speed: '⚡⚡⚡⚡', multimodal: true, reasoning: false, badge: null },
  { name: 'Claude Opus 4', org: 'Anthropic', icon: '👑', context: '200K', price: '$15.00', speed: '⚡⚡', multimodal: true, reasoning: true, badge: 'new' },
  { name: 'Claude Sonnet 4.5', org: 'Anthropic', icon: '👑', context: '200K', price: '$3.00', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: null },
  { name: 'Gemini 2.0 Flash', org: 'Google', icon: '🔬', context: '1M', price: '$0.10', speed: '⚡⚡⚡⚡', multimodal: true, reasoning: false, badge: null },
  { name: 'Gemini 2.5 Pro', org: 'Google', icon: '🔬', context: '1M', price: '$1.25', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: null },
  { name: 'Llama 4 Scout', org: 'Meta', icon: '🌐', context: '10M', price: 'Free', speed: '⚡⚡⚡', multimodal: true, reasoning: false, badge: 'open' },
  { name: 'DeepSeek V3', org: 'DeepSeek', icon: '🔍', context: '128K', price: '$0.14', speed: '⚡⚡⚡', multimodal: false, reasoning: false, badge: 'open' },
  { name: 'Mistral Large 3', org: 'Mistral', icon: '💨', context: '128K', price: '$3.00', speed: '⚡⚡⚡', multimodal: false, reasoning: true, badge: null },
  { name: 'Grok 3 Beta', org: 'xAI', icon: '✖️', context: '131K', price: '$3.00', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: null },
  { name: 'Qwen2.5 72B', org: 'Alibaba', icon: '🌸', context: '128K', price: '$0.40', speed: '⚡⚡⚡', multimodal: false, reasoning: false, badge: 'open' },
  { name: 'Command R+', org: 'Cohere', icon: '🔗', context: '128K', price: '$2.50', speed: '⚡⚡⚡', multimodal: false, reasoning: false, badge: null },
];

// Trending models
export const TRENDING_MODELS = [
  {
    id: 'o3-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o3-mini',
    org: 'OpenAI',
    desc: 'Fast, affordable reasoning model. Excels at math, science, and code.',
    badge: '🔥 Trending',
    badgeColor: '#FF4757',
    rating: 4.8,
    price: '$1.10/1M tk',
  },
  {
    id: 'claude-sonnet-4-5',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Sonnet 4.5',
    org: 'Anthropic',
    desc: 'Best blend of speed and intelligence. Ideal for agentic workflows.',
    badge: '✨ Popular',
    badgeColor: '#1E4DA8',
    rating: 4.7,
    price: '$3.00/1M tk',
  },
  {
    id: 'gemini-flash-2',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini Flash 2.0',
    org: 'Google',
    desc: 'Incredibly fast multimodal responses. Real-time audio and video.',
    badge: '⚡ Fast',
    badgeColor: '#0A5E49',
    rating: 4.6,
    price: '$0.10/1M tk',
  },
  {
    id: 'deepseek-r2',
    icon: '🔍',
    bg: '#EBF0FC',
    name: 'DeepSeek R2',
    org: 'DeepSeek',
    desc: 'Next-gen reasoning model rivaling o3. Open weights available.',
    badge: '🆕 New',
    badgeColor: '#0A5E49',
    rating: 4.7,
    price: '$0.55/1M tk',
  },
  {
    id: 'grok-3',
    icon: '✖️',
    bg: '#F0F0F0',
    name: 'Grok 3 Beta',
    org: 'xAI',
    desc: 'Real-time internet access. Excels at reasoning and data analysis.',
    badge: '🔥 Hot',
    badgeColor: '#FF4757',
    rating: 4.5,
    price: '$3.00/1M tk',
  },
];

// Budget tiers
export const BUDGET_TIERS = [
  {
    icon: '🆓',
    label: 'Free Tier',
    desc: 'No cost, no credit card',
    color: '#0A5E49',
    bg: '#E2F5EF',
    models: ['Llama 4 Scout', 'Gemma 3', 'DeepSeek V3', 'Phi-4', 'Qwen2.5'],
  },
  {
    icon: '💵',
    label: 'Budget',
    desc: '$0 – $5 per 1M tokens',
    color: '#1E4DA8',
    bg: '#EBF0FC',
    models: ['Gemini Flash', 'DeepSeek V3', 'Claude Haiku', 'GPT-4.1 Mini', 'Mistral 7B'],
  },
  {
    icon: '🏢',
    label: 'Mid-Range',
    desc: '$5 – $30 per 1M tokens',
    color: '#8A5A00',
    bg: '#FDF5E0',
    models: ['GPT-4.1', 'Mistral Large', 'Claude Sonnet', 'Grok 3', 'Command R+'],
  },
  {
    icon: '👑',
    label: 'Premium',
    desc: '$30+ per 1M tokens',
    color: '#9B2042',
    bg: '#FDEDF1',
    models: ['Claude Opus 4', 'GPT-4.5', 'Gemini Ultra', 'o3', 'GPT-4o'],
  },
];

// Use cases
export const USE_CASES = [
  { icon: '🤖', label: 'AI Assistant Trainer', tags: ['Chat', 'Code'] },
  { icon: '💻', label: 'Code Generator', tags: ['Code', 'Debug'] },
  { icon: '📝', label: 'Content Writer', tags: ['Write', 'SEO'] },
  { icon: '📊', label: 'Data Analyst', tags: ['CSV', 'Charts'] },
  { icon: '🎨', label: 'Image Creator', tags: ['Art', 'Design'] },
  { icon: '🌐', label: 'Translator', tags: ['100+ langs'] },
  { icon: '🔍', label: 'Research Assistant', tags: ['Papers', 'Summary'] },
  { icon: '💼', label: 'Business Advisor', tags: ['Strategy', 'Plans'] },
];

// Feature cards for "Built for every builder"
export const BUILDER_FEATURES = [
  {
    icon: '🔍',
    title: 'Guided Discovery',
    desc: 'Smart questionnaire matches you to the perfect AI model for your specific use case.',
  },
  {
    icon: '🔒',
    title: 'Privacy-Preserving RAG',
    desc: 'Build RAG pipelines with enterprise-grade data privacy and local model options.',
  },
  {
    icon: '⚖️',
    title: 'Legal AI Platform',
    desc: 'Purpose-built models for contract analysis, compliance, and legal research.',
  },
  {
    icon: '💰',
    title: 'Flexible Pricing',
    desc: 'Compare costs across providers. Switch models without changing your code.',
  },
  {
    icon: '📊',
    title: 'Live Benchmark Stats',
    desc: 'Real-time performance metrics, latency data, and quality scores.',
  },
  {
    icon: '🤖',
    title: 'Beyond Chat',
    desc: 'Build autonomous agents, pipelines, and multi-model workflows with ease.',
  },
];
