// AI Labs
export const AI_LABS = [
  { id: 'openai', name: 'OpenAI', icon: '🧠', color: '#10A37F' },
  { id: 'anthropic', name: 'Anthropic', icon: '👑', color: '#C8622A' },
  { id: 'google', name: 'Google DeepMind', icon: '🔬', color: '#4285F4' },
  { id: 'meta', name: 'Meta AI', icon: '🌐', color: '#0668E1' },
  { id: 'mistral', name: 'Mistral AI', icon: '💨', color: '#FF7000' },
  { id: 'cohere', name: 'Cohere', icon: '🔗', color: '#39594D' },
  { id: 'nvidia', name: 'NVIDIA', icon: '⚡', color: '#76B900' },
  { id: 'deepseek', name: 'DeepSeek', icon: '🔍', color: '#4B6BFB' },
  { id: 'qwen', name: 'Qwen', icon: '🌸', color: '#FF6B6B' },
  { id: 'microsoft', name: 'Microsoft', icon: '🪟', color: '#00A4EF' },
  { id: 'amazon', name: 'Amazon Bedrock', icon: '📦', color: '#FF9900' },
  { id: 'xai', name: 'xAI', icon: '✖️', color: '#1DA1F2' },
  { id: 'stability', name: 'Stability AI', icon: '🎨', color: '#7B68EE' },
  { id: 'perplexity', name: 'Perplexity', icon: '🔎', color: '#20808D' },
  { id: 'together', name: 'Together AI', icon: '🤝', color: '#6C63FF' },
  { id: 'moonshot', name: 'Moonshot AI', icon: '🌙', color: '#6B5CE7' },
  { id: 'zhipu', name: 'Zhipu AI', icon: '🔷', color: '#3B82F6' },
  { id: 'baidu', name: 'Baidu', icon: '🔴', color: '#DE1F1F' },
  { id: 'ai21', name: 'AI21 Labs', icon: '🟣', color: '#7C3AED' },
  { id: 'inflection', name: 'Inflection AI', icon: '💜', color: '#8B5CF6' },
  { id: 'allenai', name: 'Allen AI', icon: '🏛', color: '#059669' },
];

// Featured Models
export const FEATURED_MODELS = [
  {
    id: 'gpt-5',
    icon: '🧠',
    bg: '#EEF2FD',
    name: 'GPT-5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'OpenAI flagship. Native agent use, advanced reasoning, 2M context.',
    tags: ['Flagship', 'Agents', 'Multimodal', 'Reasoning'],
    badge: 'hot' as const,
    rating: 4.9,
    reviews: 4210,
    price: '$7.50/1M tk',
    priceStart: 7.5,
    types: ['language', 'vision', 'code'],
  },
  {
    id: 'claude-opus-4.6',
    icon: '👑',
    bg: '#E2F5EF',
    name: 'Claude Opus 4.6',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Most intelligent Claude. Adaptive Thinking, 1M context, Extended Thinking.',
    tags: ['Agents', 'Coding', 'Extended Thinking'],
    badge: 'hot' as const,
    rating: 4.9,
    reviews: 2240,
    price: '$5/1M tk',
    priceStart: 5,
    types: ['language', 'code'],
  },
  {
    id: 'gemini-3.1-pro',
    icon: '🔬',
    bg: '#FDF5E0',
    name: 'Gemini 3.1 Pro',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Deep reasoning with 5M context and Thought Signatures.',
    tags: ['Deep Reasoning', '5M Context', 'Thought Signatures'],
    badge: 'new' as const,
    rating: 4.7,
    reviews: 1450,
    price: '$2/1M tk',
    priceStart: 2,
    types: ['language', 'vision'],
  },
  {
    id: 'llama-4-maverick',
    icon: '🦙',
    bg: '#EEEDFE',
    name: 'Llama 4 Maverick',
    lab: 'meta',
    org: 'Meta',
    desc: '400B MoE with multimodal understanding. Top open-source.',
    tags: ['Open Source', '400B MoE', 'Multimodal'],
    badge: 'hot' as const,
    rating: 4.6,
    reviews: 2950,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'vision', 'code', 'open'],
  },
  {
    id: 'grok-4',
    icon: '𝕏',
    bg: '#F2F2F2',
    name: 'Grok-4',
    lab: 'xai',
    org: 'xAI',
    desc: 'Most intelligent Grok. Real-time X data, deep reasoning, 2M context.',
    tags: ['Flagship', 'Real-Time', 'Deep Reasoning'],
    badge: 'new' as const,
    rating: 4.6,
    reviews: 780,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language', 'vision'],
  },
  {
    id: 'kimi-k2.5',
    icon: '🌙',
    bg: '#F0EEFF',
    name: 'Kimi K2.5',
    lab: 'moonshot',
    org: 'Moonshot AI',
    desc: 'Agent Swarm Orchestration with 262K context. Visual coding and multi-agent RAG.',
    tags: ['Agent Swarm', 'Multi-Agent', 'RAG'],
    badge: 'new' as const,
    rating: 4.5,
    reviews: 390,
    price: '$0.60/1M tk',
    priceStart: 0.6,
    types: ['language', 'vision', 'code'],
  },
];

// Flagship comparison models
export const FLAGSHIP_MODELS = [
  { name: 'GPT-5', org: 'OpenAI', icon: '🧠', context: '2M', price: '$7.50', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'hot' },
  { name: 'GPT-5 Turbo', org: 'OpenAI', icon: '⚡', context: '2M', price: '$2.50', speed: '⚡⚡⚡⚡', multimodal: true, reasoning: true, badge: 'hot' },
  { name: 'Claude Opus 4.6', org: 'Anthropic', icon: '👑', context: '1M', price: '$5.00', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'hot' },
  { name: 'Claude Sonnet 4.6', org: 'Anthropic', icon: '⚡', context: '1M', price: '$3.00', speed: '⚡⚡⚡⚡', multimodal: true, reasoning: true, badge: 'new' },
  { name: 'Gemini 3.1 Pro', org: 'Google', icon: '🔬', context: '5M', price: '$2.00', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'new' },
  { name: 'Gemini 2.5 Pro', org: 'Google', icon: '💎', context: '1M', price: '$1.25', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'hot' },
  { name: 'Llama 4 Maverick', org: 'Meta', icon: '🦙', context: '400B MoE', price: 'Free', speed: '⚡⚡⚡', multimodal: true, reasoning: false, badge: 'hot' },
  { name: 'Llama 4 Scout', org: 'Meta', icon: '🌟', context: '128K', price: 'Free', speed: '⚡⚡⚡', multimodal: true, reasoning: false, badge: 'open' },
  { name: 'Grok-4', org: 'xAI', icon: '𝕏', context: '2M', price: '$3.00', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'new' },
  { name: 'DeepSeek-R1', org: 'DeepSeek', icon: '🔬', context: '128K', price: '$0.14', speed: '⚡⚡⚡', multimodal: false, reasoning: true, badge: 'open' },
  { name: 'Mistral Large 3', org: 'Mistral', icon: '🌀', context: '128K', price: '$2.00', speed: '⚡⚡⚡', multimodal: false, reasoning: true, badge: 'new' },
  { name: 'Kimi K2.5', org: 'Moonshot', icon: '🌙', context: '262K', price: '$0.60', speed: '⚡⚡⚡', multimodal: true, reasoning: true, badge: 'new' },
];

// Trending models
export const TRENDING_MODELS = [
  {
    id: 'gpt-5-turbo',
    icon: '⚡',
    bg: '#EEF2FD',
    name: 'GPT-5 Turbo',
    org: 'OpenAI',
    desc: 'Fast, cost-effective GPT-5 for high-volume deployments.',
    badge: '🔥 Trending',
    badgeColor: '#FF4757',
    rating: 4.8,
    price: '$2.50/1M tk',
  },
  {
    id: 'claude-sonnet-4.6',
    icon: '⚡',
    bg: '#E2F5EF',
    name: 'Claude Sonnet 4.6',
    org: 'Anthropic',
    desc: 'Best speed/intelligence balance. Adaptive Thinking, 1M context.',
    badge: '✨ Popular',
    badgeColor: '#1E4DA8',
    rating: 4.8,
    price: '$3.00/1M tk',
  },
  {
    id: 'gemini-2.5-pro',
    icon: '💎',
    bg: '#FDF5E0',
    name: 'Gemini 2.5 Pro',
    org: 'Google',
    desc: 'SOTA reasoning with 1M context. Best on math, science, and coding.',
    badge: '⚡ SOTA',
    badgeColor: '#0A5E49',
    rating: 4.8,
    price: '$1.25/1M tk',
  },
  {
    id: 'deepseek-r1',
    icon: '🔬',
    bg: '#EAF3DE',
    name: 'DeepSeek-R1',
    org: 'DeepSeek',
    desc: 'Formal theorem proving in Lean 4. Open weights.',
    badge: '🆕 New',
    badgeColor: '#0A5E49',
    rating: 4.6,
    price: '$0.14/1M tk',
  },
  {
    id: 'grok-4-fast',
    icon: '𝕏',
    bg: '#F2F2F2',
    name: 'Grok-4 Fast',
    org: 'xAI',
    desc: '4-agent architecture with real-time X data access.',
    badge: '🔥 Hot',
    badgeColor: '#FF4757',
    rating: 4.5,
    price: '$0.20/1M tk',
  },
];

// Budget tiers
export const BUDGET_TIERS = [
  {
    icon: '🆓',
    label: 'Free Tier',
    desc: 'No cost, no credit card',
    color: '#0A5E49',
    bg: '#E2F5EF',
    models: ['Llama 4 Maverick', 'Llama 4 Scout', 'DeepSeek-V3', 'Phi-4', 'Qwen2.5-72B', 'OLMo-3'],
  },
  {
    icon: '💵',
    label: 'Budget',
    desc: '$0 – $2 per 1M tokens',
    color: '#1E4DA8',
    bg: '#EBF0FC',
    models: ['Gemini 3.1 Flash-Lite', 'Mistral Medium', 'Nemotron Nano', 'GPT-4.1-mini', 'Claude Haiku 4.5'],
  },
  {
    icon: '🏢',
    label: 'Mid-Range',
    desc: '$2 – $10 per 1M tokens',
    color: '#8A5A00',
    bg: '#FDF5E0',
    models: ['Claude Sonnet 4.6', 'Claude Haiku 4.5', 'Gemini 3.1 Pro', 'GPT-5.4', 'Qwen3-Max'],
  },
  {
    icon: '👑',
    label: 'Premium',
    desc: '$10+ per 1M tokens',
    color: '#9B2042',
    bg: '#FDEDF1',
    models: ['Claude Opus 4.6', 'Sora 2 Pro', 'gpt-image-1.5', 'o3', 'Nova Premier'],
  },
];

// Use cases
export const USE_CASES = [
  { icon: '💻', label: 'Code Generation', tags: ['Claude Opus 4.6', 'Devstral 2', 'GPT-5.4', 'Qwen3-Coder'], action: 'Start building →' },
  { icon: '🎨', label: 'Image Generation', tags: ['Sora 2', 'gpt-image-1.5', 'Flux 1.1', 'Ideogram 3'], action: 'Create images →' },
  { icon: '🤖', label: 'AI Agents', tags: ['GPT-5.4', 'Claude Opus 4.6', 'Kimi K2.5', 'Grok-4-1'], action: 'Build agents →' },
  { icon: '📄', label: 'Document Analysis', tags: ['Claude Sonnet 4.6', 'Gemini 3.1 Pro', 'Nemotron Ultra'], action: 'Analyse docs →' },
  { icon: '🎵', label: 'Audio & Music', tags: ['Suno v4', 'MusicGen', 'Whisper V3', 'Bark'], action: 'Generate audio →' },
  { icon: '🌐', label: 'Multilingual / Translation', tags: ['Qwen3-Max', 'Gemini 3.1 Flash-Lite', 'GLM-4.7'], action: 'Go multilingual →' },
  { icon: '📊', label: 'Data Analysis', tags: ['Claude Opus 4.6', 'GPT-5', 'Gemini 2.5 Pro'], action: 'Analyse data →' },
  { icon: '🔬', label: 'Math & Research', tags: ['DeepSeek-R1', 'QwQ-32B', 'Gemini 3.1 Pro'], action: 'Start researching →' },
];

// Feature cards for "Built for every builder"
export const BUILDER_FEATURES = [
  {
    icon: '🔍',
    title: 'Guided Discovery',
    desc: 'Smart questionnaire matches you to the perfect AI model for your specific use case.',
  },
  {
    icon: '🔒',
    title: 'Privacy-Preserving RAG',
    desc: 'Build RAG pipelines with enterprise-grade data privacy and local model options.',
  },
  {
    icon: '⚖️',
    title: 'Legal AI Platform',
    desc: 'Purpose-built models for contract analysis, compliance, and legal research.',
  },
  {
    icon: '💰',
    title: 'Flexible Pricing',
    desc: 'Compare costs across providers. Switch models without changing your code.',
  },
  {
    icon: '📊',
    title: 'Live Benchmark Stats',
    desc: 'Real-time performance metrics, latency data, and quality scores.',
  },
  {
    icon: '🤖',
    title: 'Beyond Chat',
    desc: 'Build autonomous agents, pipelines, and multi-model workflows with ease.',
  },
];
