import type { ModelData } from '@/components/models/ModelCard';

export const MARKETPLACE_MODELS: ModelData[] = [
  // Row 1
  {
    id: 'gpt-5',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'OpenAI flagship. Better instruction-following and extended multi-task memory.',
    tags: ['Language', 'Vision', 'Code'],
    badge: 'hot',
    rating: 4.9,
    reviews: 12432,
    price: '$10/1M tk',
    priceStart: 10,
    types: ['language', 'vision', 'code'],
  },
  {
    id: 'gpt-5.2',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5.2',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Mini GPT-5 outputs with improved instruction-following and multimodal features.',
    tags: ['Language', 'Multimodal', 'Instruction'],
    badge: 'new',
    rating: 4.8,
    reviews: 4823,
    price: '$6/1M tk',
    priceStart: 6,
    types: ['language', 'vision'],
  },
  {
    id: 'gpt-5-turbo',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5 Turbo',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Fast, cost-effective GPT-5 for high-volume long-form generation.',
    tags: ['Language', 'Fast', 'High Volume'],
    rating: 4.7,
    reviews: 6321,
    price: '$5/1M tk',
    priceStart: 5,
    types: ['language'],
  },
  {
    id: 'gpt-4.5',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Bridging model with improved creativity and long-form generation.',
    tags: ['Language', 'Long-form'],
    badge: null,
    rating: 4.7,
    reviews: 8901,
    price: '$7.50/1M tk',
    priceStart: 7.5,
    types: ['language'],
  },
  {
    id: 'gpt-4.1',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.1',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Optimised for coding task instruction-following with 1M context window.',
    tags: ['Code', 'Instruction', 'Language'],
    badge: null,
    rating: 4.8,
    reviews: 11725,
    price: '$2/1M tk',
    priceStart: 2,
    types: ['language', 'code'],
  },
  // Row 2
  {
    id: 'gpt-4.1-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.1-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Lightweight GPT-4.1 for fast, affordable everyday tasks.',
    tags: ['Language', 'Fast', 'Multimodal'],
    badge: null,
    rating: 4.6,
    reviews: 9234,
    price: '$0.40/1M tk',
    priceStart: 0.4,
    types: ['language'],
  },
  {
    id: 'gpt-4o',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4o',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Multimodal flagship combining text, vision, and audio in one unified model.',
    tags: ['Language', 'Vision', 'Audio', 'Code'],
    badge: null,
    rating: 4.7,
    reviews: 15234,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language', 'vision', 'audio'],
  },
  {
    id: 'gpt-4o-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4o-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Affordable, lightweight chat and vision model for everyday tasks.',
    tags: ['Language', 'Vision', 'Fast'],
    badge: null,
    rating: 4.5,
    reviews: 18203,
    price: '$0.15/1M tk',
    priceStart: 0.15,
    types: ['language', 'vision'],
  },
  {
    id: 'o3',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o3',
    lab: 'openai',
    org: 'OpenAI',
    desc: "OpenAI's advanced reasoning model for multi-step thoughts for complex tasks.",
    tags: ['Reasoning', 'Code', 'Analysis'],
    badge: 'hot',
    rating: 4.9,
    reviews: 7823,
    price: '$10/1M tk',
    priceStart: 10,
    types: ['language', 'code'],
  },
  {
    id: 'o3-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o3-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Cost-effective reasoning model. Best value at $1.10/1M tokens for complex tasks.',
    tags: ['Reasoning', 'Code', 'Efficient'],
    badge: null,
    rating: 4.7,
    reviews: 10432,
    price: '$1.10/1M tk',
    priceStart: 1.1,
    types: ['language'],
  },
  // Row 3
  {
    id: 'o4-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o4-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: "OpenAI's compact reasoning model cost-effective $1.10/1M, strong at STEM.",
    tags: ['Reasoning', 'STEM', 'Code'],
    badge: null,
    rating: 4.7,
    reviews: 5621,
    price: '$1.10/1M tk',
    priceStart: 1.1,
    types: ['language'],
  },
  {
    id: 'claude-opus-4-6',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Opus 4.6',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Most intelligent Claude model. Extended thinking with 200K context and creative tasks.',
    tags: ['Language', 'Reasoning', 'Extended Thinking'],
    badge: 'new',
    rating: 4.9,
    reviews: 3241,
    price: '$15/1M tk',
    priceStart: 15,
    types: ['language'],
  },
  {
    id: 'claude-sonnet-4-5',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Sonnet 4.5',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Most intelligent Claude: flexible intelligence with extended thinking and 200K context.',
    tags: ['Language', 'Reasoning', 'Extended Thinking', 'Coding'],
    badge: null,
    rating: 4.8,
    reviews: 4523,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'claude-opus-4',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Opus 4',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Previous gen Opus: advanced content and reasoning with parallel tool use.',
    tags: ['Language', 'Analysis', 'Code'],
    badge: null,
    rating: 4.8,
    reviews: 6712,
    price: '$15/1M tk',
    priceStart: 15,
    types: ['language'],
  },
  {
    id: 'claude-sonnet-4-6',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Sonnet 4.6',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Opus 4 – More agentic; long document processing, and hybrid writing.',
    tags: ['Analysis', 'Long Documents', 'Writing'],
    badge: null,
    rating: 4.7,
    reviews: 2981,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'gemini-2-5-pro',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 2.5 Pro',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Google flagship with 1M context, multimodal capabilities and advanced reasoning.',
    tags: ['Language', 'Vision', 'Reasoning'],
    badge: 'hot',
    rating: 4.8,
    reviews: 8234,
    price: '$1.25/1M tk',
    priceStart: 1.25,
    types: ['language', 'vision'],
  },
  {
    id: 'gemini-2-flash',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 2.0 Flash',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Ultra-fast multimodal model with real-time streaming and 1M context window.',
    tags: ['Language', 'Vision', 'Fast'],
    badge: null,
    rating: 4.7,
    reviews: 11456,
    price: '$0.10/1M tk',
    priceStart: 0.1,
    types: ['language', 'vision', 'audio'],
  },
  {
    id: 'gemma-3',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemma 3',
    lab: 'google',
    org: 'Google DeepMind',
    desc: "Google's open-source family. Strong at coding and efficient on consumer hardware.",
    tags: ['Language', 'Open Source', 'Code'],
    badge: 'open',
    rating: 4.5,
    reviews: 6789,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },
  {
    id: 'llama-4-scout',
    icon: '🌐',
    bg: '#E2F5EF',
    name: 'Llama 4 Scout',
    lab: 'meta',
    org: 'Meta AI',
    desc: 'Open-source multimodal model with 10M context and 17B active parameters.',
    tags: ['Language', 'Open Source', 'Multimodal'],
    badge: 'open',
    rating: 4.6,
    reviews: 9876,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'vision', 'open'],
  },
  {
    id: 'deepseek-v3',
    icon: '🔍',
    bg: '#EBF0FC',
    name: 'DeepSeek V3',
    lab: 'deepseek',
    org: 'DeepSeek',
    desc: 'Cost-efficient frontier model with exceptional math and coding capabilities.',
    tags: ['Language', 'Code', 'Open Source'],
    badge: 'open',
    rating: 4.7,
    reviews: 12045,
    price: '$0.14/1M tk',
    priceStart: 0.14,
    types: ['language', 'code', 'open'],
  },
  {
    id: 'mistral-large-3',
    icon: '💨',
    bg: '#FFF3E8',
    name: 'Mistral Large 3',
    lab: 'mistral',
    org: 'Mistral AI',
    desc: 'Top-tier reasoning with multilingual support and advanced function calling.',
    tags: ['Language', 'Code', 'Multilingual'],
    badge: null,
    rating: 4.5,
    reviews: 7432,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language', 'code'],
  },
  {
    id: 'grok-3',
    icon: '✖️',
    bg: '#F0F0F0',
    name: 'Grok 3 Beta',
    lab: 'xai',
    org: 'xAI',
    desc: 'Real-time internet access model. Excels at reasoning and data analysis tasks.',
    tags: ['Language', 'Reasoning', 'Code'],
    badge: null,
    rating: 4.5,
    reviews: 5432,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'phi-4',
    icon: '🪟',
    bg: '#EBF0FC',
    name: 'Phi-4',
    lab: 'microsoft',
    org: 'Microsoft',
    desc: 'Small but mighty. 14B parameters with strong reasoning-to-size ratio.',
    tags: ['Language', 'Reasoning', 'Efficient'],
    badge: null,
    rating: 4.4,
    reviews: 4123,
    price: '$0.07/1M tk',
    priceStart: 0.07,
    types: ['language'],
  },
  {
    id: 'qwen-2-5-72b',
    icon: '🌸',
    bg: '#FDEDF1',
    name: 'Qwen 2.5 72B',
    lab: 'qwen',
    org: 'Alibaba',
    desc: 'Alibaba open-source flagship with outstanding code and math capabilities.',
    tags: ['Language', 'Code', 'Open Source'],
    badge: 'open',
    rating: 4.6,
    reviews: 8543,
    price: '$0.40/1M tk',
    priceStart: 0.4,
    types: ['language', 'code', 'open'],
  },
  {
    id: 'command-r-plus',
    icon: '🔗',
    bg: '#E2F5EF',
    name: 'Command R+',
    lab: 'cohere',
    org: 'Cohere',
    desc: 'Enterprise RAG specialist with grounding, citations and tool use built-in.',
    tags: ['Language', 'Analysis', 'Multilingual'],
    badge: null,
    rating: 4.3,
    reviews: 3214,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language'],
  },

  // ─── Additional OpenAI models ───
  {
    id: 'dall-e-3',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'DALL-E 3',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'State-of-the-art image generation with natural language prompts and fine detail.',
    tags: ['Image', 'Generation', 'Creative'],
    badge: null,
    rating: 4.6,
    reviews: 9872,
    price: '$0.04/img',
    priceStart: 0.04,
    types: ['image'],
  },
  {
    id: 'whisper-large',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'Whisper Large',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Robust speech recognition model trained on 680K hours of multilingual audio data.',
    tags: ['Audio', 'Transcription', 'Multilingual'],
    badge: null,
    rating: 4.7,
    reviews: 6543,
    price: '$0.006/min',
    priceStart: 0.006,
    types: ['audio'],
  },

  // ─── Additional Anthropic models ───
  {
    id: 'claude-haiku-3-5',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude 3.5 Haiku',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Fastest Claude model optimized for speed and cost without sacrificing quality.',
    tags: ['Language', 'Fast', 'Code'],
    badge: null,
    rating: 4.5,
    reviews: 5876,
    price: '$0.80/1M tk',
    priceStart: 0.8,
    types: ['language'],
  },

  // ─── Additional Google DeepMind models ───
  {
    id: 'gemini-2-5-flash',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 2.5 Flash',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Fast and efficient Gemini model with built-in thinking and 1M context window.',
    tags: ['Language', 'Vision', 'Fast'],
    badge: 'new',
    rating: 4.7,
    reviews: 5432,
    price: '$0.15/1M tk',
    priceStart: 0.15,
    types: ['language', 'vision'],
  },
  {
    id: 'imagen-3',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Imagen 3',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Google highest-quality text-to-image model with photorealistic output and editing.',
    tags: ['Image', 'Generation', 'Creative'],
    badge: null,
    rating: 4.5,
    reviews: 3214,
    price: '$0.03/img',
    priceStart: 0.03,
    types: ['image'],
  },

  // ─── Additional Meta AI models ───
  {
    id: 'llama-4-maverick',
    icon: '🌐',
    bg: '#E2F5EF',
    name: 'Llama 4 Maverick',
    lab: 'meta',
    org: 'Meta AI',
    desc: '400B parameter open-source model with 256 experts and 17B active parameters.',
    tags: ['Language', 'Open Source', 'Multimodal'],
    badge: 'open',
    rating: 4.5,
    reviews: 7654,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },
  {
    id: 'llama-3-3-70b',
    icon: '🌐',
    bg: '#E2F5EF',
    name: 'Llama 3.3 70B',
    lab: 'meta',
    org: 'Meta AI',
    desc: 'Versatile 70B open-source model with strong multilingual and coding performance.',
    tags: ['Language', 'Open Source', 'Code'],
    badge: null,
    rating: 4.4,
    reviews: 8901,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'code', 'open'],
  },

  // ─── Additional DeepSeek models ───
  {
    id: 'deepseek-r1',
    icon: '🔍',
    bg: '#EBF0FC',
    name: 'DeepSeek R1',
    lab: 'deepseek',
    org: 'DeepSeek',
    desc: 'Open-source reasoning model with chain-of-thought for math and logic tasks.',
    tags: ['Reasoning', 'Code', 'Open Source'],
    badge: 'open',
    rating: 4.6,
    reviews: 7654,
    price: '$0.55/1M tk',
    priceStart: 0.55,
    types: ['language', 'code', 'open'],
  },
  {
    id: 'deepseek-r2',
    icon: '🔍',
    bg: '#EBF0FC',
    name: 'DeepSeek R2',
    lab: 'deepseek',
    org: 'DeepSeek',
    desc: 'Next-gen reasoning model rivaling o3. Open weights with enhanced chain-of-thought.',
    tags: ['Reasoning', 'Code', 'Open Source'],
    badge: 'new',
    rating: 4.7,
    reviews: 4321,
    price: '$0.55/1M tk',
    priceStart: 0.55,
    types: ['language', 'code', 'open'],
  },

  // ─── Additional Mistral AI models ───
  {
    id: 'mistral-small-3-1',
    icon: '💨',
    bg: '#FFF3E8',
    name: 'Mistral Small 3.1',
    lab: 'mistral',
    org: 'Mistral AI',
    desc: 'Lightweight 24B model with vision capabilities. Ideal for fast, low-cost tasks.',
    tags: ['Language', 'Vision', 'Fast'],
    badge: null,
    rating: 4.3,
    reviews: 4321,
    price: '$0.15/1M tk',
    priceStart: 0.15,
    types: ['language', 'vision'],
  },
  {
    id: 'codestral',
    icon: '💨',
    bg: '#FFF3E8',
    name: 'Codestral',
    lab: 'mistral',
    org: 'Mistral AI',
    desc: 'Purpose-built 22B code model. Excels at generation, completion, and code review.',
    tags: ['Code', 'Generation', 'Review'],
    badge: null,
    rating: 4.4,
    reviews: 5678,
    price: '$0.30/1M tk',
    priceStart: 0.3,
    types: ['language', 'code'],
  },
  {
    id: 'pixtral-large',
    icon: '💨',
    bg: '#FFF3E8',
    name: 'Pixtral Large',
    lab: 'mistral',
    org: 'Mistral AI',
    desc: '124B multimodal model combining vision understanding with strong text reasoning.',
    tags: ['Vision', 'Language', 'Multimodal'],
    badge: null,
    rating: 4.4,
    reviews: 2345,
    price: '$2.00/1M tk',
    priceStart: 2,
    types: ['language', 'vision'],
  },

  // ─── Additional xAI models ───
  {
    id: 'grok-3-mini',
    icon: '✖️',
    bg: '#F0F0F0',
    name: 'Grok 3 Mini',
    lab: 'xai',
    org: 'xAI',
    desc: 'Compact Grok model with real-time search and fast responses at lower cost.',
    tags: ['Language', 'Fast', 'Reasoning'],
    badge: null,
    rating: 4.3,
    reviews: 3456,
    price: '$0.30/1M tk',
    priceStart: 0.3,
    types: ['language'],
  },

  // ─── Additional Microsoft models ───
  {
    id: 'phi-4-multimodal',
    icon: '🪟',
    bg: '#EBF0FC',
    name: 'Phi-4 Multimodal',
    lab: 'microsoft',
    org: 'Microsoft',
    desc: 'Compact multimodal model handling text, images, and speech in a single architecture.',
    tags: ['Multimodal', 'Vision', 'Audio'],
    badge: null,
    rating: 4.3,
    reviews: 2876,
    price: '$0.10/1M tk',
    priceStart: 0.1,
    types: ['language', 'vision', 'audio'],
  },

  // ─── Additional Qwen models ───
  {
    id: 'qwen-2-5-coder-32b',
    icon: '🌸',
    bg: '#FDEDF1',
    name: 'Qwen 2.5 Coder 32B',
    lab: 'qwen',
    org: 'Alibaba',
    desc: 'Specialized coding model with deep understanding of 90+ programming languages.',
    tags: ['Code', 'Open Source', 'Generation'],
    badge: null,
    rating: 4.5,
    reviews: 4567,
    price: '$0.18/1M tk',
    priceStart: 0.18,
    types: ['language', 'code', 'open'],
  },
  {
    id: 'qwen-vl-max',
    icon: '🌸',
    bg: '#FDEDF1',
    name: 'Qwen VL Max',
    lab: 'qwen',
    org: 'Alibaba',
    desc: 'Powerful vision-language model for image understanding, OCR, and visual QA.',
    tags: ['Vision', 'Language', 'Multimodal'],
    badge: null,
    rating: 4.4,
    reviews: 2345,
    price: '$0.80/1M tk',
    priceStart: 0.8,
    types: ['language', 'vision'],
  },

  // ─── Additional Cohere models ───
  {
    id: 'command-a',
    icon: '🔗',
    bg: '#E2F5EF',
    name: 'Command A',
    lab: 'cohere',
    org: 'Cohere',
    desc: 'Latest enterprise model with agentic capabilities and 256K context window.',
    tags: ['Language', 'Enterprise', 'Agentic'],
    badge: 'new',
    rating: 4.5,
    reviews: 1876,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language'],
  },
  {
    id: 'embed-4',
    icon: '🔗',
    bg: '#E2F5EF',
    name: 'Embed 4',
    lab: 'cohere',
    org: 'Cohere',
    desc: 'Multimodal embedding model for text and images with state-of-the-art retrieval.',
    tags: ['Embeddings', 'Search', 'Multimodal'],
    badge: null,
    rating: 4.6,
    reviews: 2345,
    price: '$0.10/1M tk',
    priceStart: 0.1,
    types: ['embeddings'],
  },

  // ─── NVIDIA ───
  {
    id: 'nemotron-4-340b',
    icon: '⚡',
    bg: '#F0F7E6',
    name: 'Nemotron 4 340B',
    lab: 'nvidia',
    org: 'NVIDIA',
    desc: 'Massive 340B parameter model excelling at instruction following and chat.',
    tags: ['Language', 'Enterprise', 'Instruction'],
    badge: null,
    rating: 4.4,
    reviews: 3456,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language'],
  },
  {
    id: 'llama-3-1-nemotron-70b',
    icon: '⚡',
    bg: '#F0F7E6',
    name: 'Llama 3.1 Nemotron 70B',
    lab: 'nvidia',
    org: 'NVIDIA',
    desc: 'NVIDIA-optimized Llama fine-tune with improved alignment and helpfulness.',
    tags: ['Language', 'Open Source', 'Fine-tuned'],
    badge: null,
    rating: 4.3,
    reviews: 2134,
    price: '$0.80/1M tk',
    priceStart: 0.8,
    types: ['language', 'open'],
  },

  // ─── Stability AI ───
  {
    id: 'stable-diffusion-3-5',
    icon: '🎨',
    bg: '#F0EBF8',
    name: 'Stable Diffusion 3.5',
    lab: 'stability',
    org: 'Stability AI',
    desc: 'Advanced diffusion model with superior text rendering and photorealistic output.',
    tags: ['Image', 'Generation', 'Creative'],
    badge: null,
    rating: 4.5,
    reviews: 8765,
    price: '$0.03/img',
    priceStart: 0.03,
    types: ['image'],
  },
  {
    id: 'stable-video-diffusion',
    icon: '🎨',
    bg: '#F0EBF8',
    name: 'Stable Video Diffusion',
    lab: 'stability',
    org: 'Stability AI',
    desc: 'Image-to-video generation model producing high-quality short video clips.',
    tags: ['Video', 'Generation', 'Creative'],
    badge: null,
    rating: 4.2,
    reviews: 3456,
    price: '$0.10/sec',
    priceStart: 0.1,
    types: ['video'],
  },

  // ─── Hugging Face ───
  {
    id: 'zephyr-7b',
    icon: '🤗',
    bg: '#FFF3E8',
    name: 'Zephyr 7B',
    lab: 'huggingface',
    org: 'Hugging Face',
    desc: 'Compact 7B model fine-tuned with DPO for strong chat and instruction following.',
    tags: ['Language', 'Open Source', 'Chat'],
    badge: null,
    rating: 4.1,
    reviews: 4567,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },
  {
    id: 'falcon-180b',
    icon: '🤗',
    bg: '#FFF3E8',
    name: 'Falcon 180B',
    lab: 'huggingface',
    org: 'Hugging Face',
    desc: 'Large 180B open-source model trained on RefinedWeb with strong zero-shot abilities.',
    tags: ['Language', 'Open Source', 'Reasoning'],
    badge: 'open',
    rating: 4.3,
    reviews: 2345,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },

  // ─── Perplexity ───
  {
    id: 'sonar-large',
    icon: '🔎',
    bg: '#E8F4F4',
    name: 'Sonar Large',
    lab: 'perplexity',
    org: 'Perplexity',
    desc: 'Pro search model with real-time web grounding and cited, accurate responses.',
    tags: ['Search', 'Language', 'Citations'],
    badge: null,
    rating: 4.5,
    reviews: 5678,
    price: '$1.00/1M tk',
    priceStart: 1,
    types: ['language'],
  },
  {
    id: 'sonar-small',
    icon: '🔎',
    bg: '#E8F4F4',
    name: 'Sonar Small',
    lab: 'perplexity',
    org: 'Perplexity',
    desc: 'Lightweight search-augmented model for fast, grounded answers at scale.',
    tags: ['Search', 'Fast', 'Language'],
    badge: null,
    rating: 4.3,
    reviews: 3456,
    price: '$0.20/1M tk',
    priceStart: 0.2,
    types: ['language'],
  },

  // ─── Together AI ───
  {
    id: 'topper-alpha',
    icon: '🤝',
    bg: '#EDE8F8',
    name: 'Topper Alpha',
    lab: 'together',
    org: 'Together AI',
    desc: 'High-performance open-source model with strong reasoning and math capabilities.',
    tags: ['Language', 'Open Source', 'Reasoning'],
    badge: null,
    rating: 4.3,
    reviews: 1234,
    price: '$0.80/1M tk',
    priceStart: 0.8,
    types: ['language'],
  },
  {
    id: 'coder-alpha',
    icon: '🤝',
    bg: '#EDE8F8',
    name: 'Coder Alpha',
    lab: 'together',
    org: 'Together AI',
    desc: 'Specialized code generation model trained on diverse programming datasets.',
    tags: ['Code', 'Open Source', 'Generation'],
    badge: null,
    rating: 4.2,
    reviews: 987,
    price: '$0.50/1M tk',
    priceStart: 0.5,
    types: ['language', 'code'],
  },

  // ─── Amazon ───
  {
    id: 'titan-text-premier',
    icon: '📦',
    bg: '#FFF3E8',
    name: 'Titan Text Premier',
    lab: 'amazon',
    org: 'Amazon',
    desc: 'AWS-native large language model for enterprise text generation and summarization.',
    tags: ['Language', 'Enterprise', 'AWS'],
    badge: null,
    rating: 4.2,
    reviews: 2345,
    price: '$2.00/1M tk',
    priceStart: 2,
    types: ['language'],
  },
  {
    id: 'titan-image-generator',
    icon: '📦',
    bg: '#FFF3E8',
    name: 'Titan Image Generator',
    lab: 'amazon',
    org: 'Amazon',
    desc: 'Enterprise-grade image generation with built-in content filtering and safety.',
    tags: ['Image', 'Generation', 'Enterprise'],
    badge: null,
    rating: 4.1,
    reviews: 1234,
    price: '$0.04/img',
    priceStart: 0.04,
    types: ['image'],
  },

  // ─── AI21 Labs ───
  {
    id: 'jurassic-2-ultra',
    icon: '🦎',
    bg: '#E8F4F4',
    name: 'Jurassic-2 Ultra',
    lab: 'ai21',
    org: 'AI21 Labs',
    desc: 'Advanced language model with custom tasks, long documents, and multilingual support.',
    tags: ['Language', 'Enterprise', 'Long-form'],
    badge: null,
    rating: 4.3,
    reviews: 3456,
    price: '$8.00/1M tk',
    priceStart: 8,
    types: ['language'],
  },
  {
    id: 'jamba-1-5-large',
    icon: '🦎',
    bg: '#E8F4F4',
    name: 'Jamba 1.5 Large',
    lab: 'ai21',
    org: 'AI21 Labs',
    desc: 'SSM-Transformer hybrid with 256K context window and fast long-context processing.',
    tags: ['Language', 'Long-form', 'Fast'],
    badge: null,
    rating: 4.4,
    reviews: 2134,
    price: '$4.00/1M tk',
    priceStart: 4,
    types: ['language'],
  },

  // ─── Inflection AI ───
  {
    id: 'inflection-3',
    icon: '💡',
    bg: '#FDF5E0',
    name: 'Inflection 3',
    lab: 'inflection',
    org: 'Inflection AI',
    desc: 'Empathetic conversational AI with strong instruction following and nuance.',
    tags: ['Language', 'Chat', 'Empathetic'],
    badge: null,
    rating: 4.3,
    reviews: 1876,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language'],
  },

  // ─── Reka AI ───
  {
    id: 'reka-core',
    icon: '🎯',
    bg: '#FDEDF1',
    name: 'Reka Core',
    lab: 'reka',
    org: 'Reka AI',
    desc: 'Multimodal model handling text, images, video, and audio with strong reasoning.',
    tags: ['Multimodal', 'Vision', 'Reasoning'],
    badge: null,
    rating: 4.4,
    reviews: 1234,
    price: '$3.00/1M tk',
    priceStart: 3,
    types: ['language', 'vision'],
  },
  {
    id: 'reka-flash',
    icon: '🎯',
    bg: '#FDEDF1',
    name: 'Reka Flash',
    lab: 'reka',
    org: 'Reka AI',
    desc: 'Fast and efficient multimodal model optimized for real-time applications.',
    tags: ['Multimodal', 'Fast', 'Vision'],
    badge: null,
    rating: 4.2,
    reviews: 987,
    price: '$0.80/1M tk',
    priceStart: 0.8,
    types: ['language', 'vision'],
  },

  // ─── 01.AI ───
  {
    id: 'yi-large',
    icon: '🔮',
    bg: '#EDE8F8',
    name: 'Yi Large',
    lab: 'yi',
    org: '01.AI',
    desc: 'High-performing bilingual model excelling at English and Chinese tasks.',
    tags: ['Language', 'Bilingual', 'Reasoning'],
    badge: null,
    rating: 4.4,
    reviews: 2345,
    price: '$3.00/1M tk',
    priceStart: 3,
    types: ['language'],
  },

  // ─── Zhipu AI ───
  {
    id: 'glm-4',
    icon: '🏔️',
    bg: '#E8F4F4',
    name: 'GLM-4',
    lab: 'zhipu',
    org: 'Zhipu AI',
    desc: 'Bilingual Chinese-English model with strong coding, reasoning, and tool use.',
    tags: ['Language', 'Code', 'Bilingual'],
    badge: null,
    rating: 4.3,
    reviews: 1876,
    price: '$1.50/1M tk',
    priceStart: 1.5,
    types: ['language', 'code'],
  },

  // ─── MiniMax ───
  {
    id: 'minimax-01',
    icon: '🎪',
    bg: '#FFF3E8',
    name: 'MiniMax 01',
    lab: 'minimax',
    org: 'MiniMax',
    desc: 'Large MoE model with 456B total parameters and 4M context for long documents.',
    tags: ['Language', 'Long-form', 'MoE'],
    badge: null,
    rating: 4.2,
    reviews: 987,
    price: '$1.00/1M tk',
    priceStart: 1,
    types: ['language'],
  },

  // ─── Databricks ───
  {
    id: 'dbrx-instruct',
    icon: '🔥',
    bg: '#FFF3E8',
    name: 'DBRX Instruct',
    lab: 'databricks',
    org: 'Databricks',
    desc: 'Open-source 132B MoE model with fine-grained expertise for coding and math.',
    tags: ['Language', 'Open Source', 'Code'],
    badge: 'open',
    rating: 4.2,
    reviews: 2345,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'code', 'open'],
  },

  // ─── Snowflake ───
  {
    id: 'arctic-instruct',
    icon: '❄️',
    bg: '#EBF0FC',
    name: 'Arctic Instruct',
    lab: 'snowflake',
    org: 'Snowflake',
    desc: 'Efficient 480B MoE model optimized for enterprise data tasks and SQL generation.',
    tags: ['Language', 'Enterprise', 'Data'],
    badge: null,
    rating: 4.1,
    reviews: 1234,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },

  // ─── Writer ───
  {
    id: 'palmyra-x-5',
    icon: '✍️',
    bg: '#E2F5EF',
    name: 'Palmyra X 5',
    lab: 'writer',
    org: 'Writer',
    desc: 'Enterprise content generation model with brand voice consistency and compliance.',
    tags: ['Language', 'Enterprise', 'Content'],
    badge: null,
    rating: 4.3,
    reviews: 1567,
    price: '$5.00/1M tk',
    priceStart: 5,
    types: ['language'],
  },

  // ─── Voyage AI ───
  {
    id: 'voyage-3',
    icon: '🧭',
    bg: '#EBF0FC',
    name: 'Voyage 3',
    lab: 'voyage',
    org: 'Voyage AI',
    desc: 'State-of-the-art embedding model with superior retrieval quality and multilingual.',
    tags: ['Embeddings', 'Search', 'RAG'],
    badge: null,
    rating: 4.5,
    reviews: 2134,
    price: '$0.06/1M tk',
    priceStart: 0.06,
    types: ['embeddings'],
  },

  // ─── Black Forest Labs ───
  {
    id: 'flux-1-1-pro',
    icon: '🌲',
    bg: '#E2F5EF',
    name: 'FLUX.1.1 Pro',
    lab: 'blackforest',
    org: 'Black Forest Labs',
    desc: 'State-of-the-art image generation with exceptional prompt following and diversity.',
    tags: ['Image', 'Generation', 'Creative'],
    badge: null,
    rating: 4.7,
    reviews: 6543,
    price: '$0.04/img',
    priceStart: 0.04,
    types: ['image'],
  },

  // ─── Runway ───
  {
    id: 'gen-3-alpha',
    icon: '🎬',
    bg: '#FDEDF1',
    name: 'Gen-3 Alpha',
    lab: 'runway',
    org: 'Runway',
    desc: 'Advanced video generation model producing cinematic clips from text and images.',
    tags: ['Video', 'Generation', 'Creative'],
    badge: 'new',
    rating: 4.4,
    reviews: 3456,
    price: '$0.05/sec',
    priceStart: 0.05,
    types: ['video'],
  },

  // ─── ElevenLabs ───
  {
    id: 'eleven-turbo-v2',
    icon: '🎙️',
    bg: '#EDE8F8',
    name: 'Eleven Turbo v2',
    lab: 'elevenlabs',
    org: 'ElevenLabs',
    desc: 'Ultra-realistic text-to-speech with voice cloning and multilingual support.',
    tags: ['Audio', 'TTS', 'Voice Clone'],
    badge: null,
    rating: 4.8,
    reviews: 8765,
    price: '$0.30/1K chars',
    priceStart: 0.3,
    types: ['audio'],
  },

  // ─── Midjourney ───
  {
    id: 'midjourney-v6-1',
    icon: '🖼️',
    bg: '#F0EBF8',
    name: 'Midjourney V6.1',
    lab: 'midjourney',
    org: 'Midjourney',
    desc: 'Industry-leading artistic image generation with exceptional aesthetics and detail.',
    tags: ['Image', 'Generation', 'Artistic'],
    badge: 'hot',
    rating: 4.9,
    reviews: 15432,
    price: '$0.05/img',
    priceStart: 0.05,
    types: ['image'],
  },
];
