import type { ModelData } from '@/components/models/ModelCard';

export const MARKETPLACE_MODELS: ModelData[] = [
  // Row 1
  {
    id: 'gpt-5',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'OpenAI flagship. Better instruction-following and extended multi-task memory.',
    tags: ['Language', 'Vision', 'Code'],
    badge: 'hot',
    rating: 4.9,
    reviews: 12432,
    price: '$10/1M tk',
    priceStart: 10,
    types: ['language', 'vision', 'code'],
  },
  {
    id: 'gpt-5.2',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5.2',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Mini GPT-5 outputs with improved instruction-following and multimodal features.',
    tags: ['Language', 'Multimodal', 'Instruction'],
    badge: 'new',
    rating: 4.8,
    reviews: 4823,
    price: '$6/1M tk',
    priceStart: 6,
    types: ['language', 'vision'],
  },
  {
    id: 'gpt-5-turbo',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-5 Turbo',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Fast, cost-effective GPT-5 for high-volume long-form generation.',
    tags: ['Language', 'Fast', 'High Volume'],
    rating: 4.7,
    reviews: 6321,
    price: '$5/1M tk',
    priceStart: 5,
    types: ['language'],
  },
  {
    id: 'gpt-4.5',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.5',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Bridging model with improved creativity and long-form generation.',
    tags: ['Language', 'Long-form'],
    badge: null,
    rating: 4.7,
    reviews: 8901,
    price: '$7.50/1M tk',
    priceStart: 7.5,
    types: ['language'],
  },
  {
    id: 'gpt-4.1',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.1',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Optimised for coding task instruction-following with 1M context window.',
    tags: ['Code', 'Instruction', 'Language'],
    badge: null,
    rating: 4.8,
    reviews: 11725,
    price: '$2/1M tk',
    priceStart: 2,
    types: ['language', 'code'],
  },
  // Row 2
  {
    id: 'gpt-4.1-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4.1-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Lightweight GPT-4.1 for fast, affordable everyday tasks.',
    tags: ['Language', 'Fast', 'Multimodal'],
    badge: null,
    rating: 4.6,
    reviews: 9234,
    price: '$0.40/1M tk',
    priceStart: 0.4,
    types: ['language'],
  },
  {
    id: 'gpt-4o',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4o',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Multimodal flagship combining text, vision, and audio in one unified model.',
    tags: ['Language', 'Vision', 'Audio', 'Code'],
    badge: null,
    rating: 4.7,
    reviews: 15234,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language', 'vision', 'audio'],
  },
  {
    id: 'gpt-4o-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'GPT-4o-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Affordable, lightweight chat and vision model for everyday tasks.',
    tags: ['Language', 'Vision', 'Fast'],
    badge: null,
    rating: 4.5,
    reviews: 18203,
    price: '$0.15/1M tk',
    priceStart: 0.15,
    types: ['language', 'vision'],
  },
  {
    id: 'o3',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o3',
    lab: 'openai',
    org: 'OpenAI',
    desc: "OpenAI's advanced reasoning model for multi-step thoughts for complex tasks.",
    tags: ['Reasoning', 'Code', 'Analysis'],
    badge: 'hot',
    rating: 4.9,
    reviews: 7823,
    price: '$10/1M tk',
    priceStart: 10,
    types: ['language', 'code'],
  },
  {
    id: 'o3-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o3-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: 'Cost-effective reasoning model. Best value at $1.10/1M tokens for complex tasks.',
    tags: ['Reasoning', 'Code', 'Efficient'],
    badge: null,
    rating: 4.7,
    reviews: 10432,
    price: '$1.10/1M tk',
    priceStart: 1.1,
    types: ['language'],
  },
  // Row 3
  {
    id: 'o4-mini',
    icon: '🧠',
    bg: '#D7F5EC',
    name: 'o4-mini',
    lab: 'openai',
    org: 'OpenAI',
    desc: "OpenAI's compact reasoning model cost-effective $1.10/1M, strong at STEM.",
    tags: ['Reasoning', 'STEM', 'Code'],
    badge: null,
    rating: 4.7,
    reviews: 5621,
    price: '$1.10/1M tk',
    priceStart: 1.1,
    types: ['language'],
  },
  {
    id: 'claude-opus-4-6',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Opus 4.6',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Most intelligent Claude model. Extended thinking with 200K context and creative tasks.',
    tags: ['Language', 'Reasoning', 'Extended Thinking'],
    badge: 'new',
    rating: 4.9,
    reviews: 3241,
    price: '$15/1M tk',
    priceStart: 15,
    types: ['language'],
  },
  {
    id: 'claude-sonnet-4-5',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Sonnet 4.5',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Most intelligent Claude: flexible intelligence with extended thinking and 200K context.',
    tags: ['Language', 'Reasoning', 'Extended Thinking', 'Coding'],
    badge: null,
    rating: 4.8,
    reviews: 4523,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'claude-opus-4',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Opus 4',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Previous gen Opus: advanced content and reasoning with parallel tool use.',
    tags: ['Language', 'Analysis', 'Code'],
    badge: null,
    rating: 4.8,
    reviews: 6712,
    price: '$15/1M tk',
    priceStart: 15,
    types: ['language'],
  },
  {
    id: 'claude-sonnet-4-6',
    icon: '👑',
    bg: '#FDF1EB',
    name: 'Claude Sonnet 4.6',
    lab: 'anthropic',
    org: 'Anthropic',
    desc: 'Opus 4 – More agentic; long document processing, and hybrid writing.',
    tags: ['Analysis', 'Long Documents', 'Writing'],
    badge: null,
    rating: 4.7,
    reviews: 2981,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'gemini-2-5-pro',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 2.5 Pro',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Google flagship with 1M context, multimodal capabilities and advanced reasoning.',
    tags: ['Language', 'Vision', 'Reasoning'],
    badge: 'hot',
    rating: 4.8,
    reviews: 8234,
    price: '$1.25/1M tk',
    priceStart: 1.25,
    types: ['language', 'vision'],
  },
  {
    id: 'gemini-2-flash',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemini 2.0 Flash',
    lab: 'google',
    org: 'Google DeepMind',
    desc: 'Ultra-fast multimodal model with real-time streaming and 1M context window.',
    tags: ['Language', 'Vision', 'Fast'],
    badge: null,
    rating: 4.7,
    reviews: 11456,
    price: '$0.10/1M tk',
    priceStart: 0.1,
    types: ['language', 'vision', 'audio'],
  },
  {
    id: 'gemma-3',
    icon: '🔬',
    bg: '#EBF0FC',
    name: 'Gemma 3',
    lab: 'google',
    org: 'Google DeepMind',
    desc: "Google's open-source family. Strong at coding and efficient on consumer hardware.",
    tags: ['Language', 'Open Source', 'Code'],
    badge: 'open',
    rating: 4.5,
    reviews: 6789,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'open'],
  },
  {
    id: 'llama-4-scout',
    icon: '🌐',
    bg: '#E2F5EF',
    name: 'Llama 4 Scout',
    lab: 'meta',
    org: 'Meta AI',
    desc: 'Open-source multimodal model with 10M context and 17B active parameters.',
    tags: ['Language', 'Open Source', 'Multimodal'],
    badge: 'open',
    rating: 4.6,
    reviews: 9876,
    price: 'Free',
    priceStart: 0,
    types: ['language', 'vision', 'open'],
  },
  {
    id: 'deepseek-v3',
    icon: '🔍',
    bg: '#EBF0FC',
    name: 'DeepSeek V3',
    lab: 'deepseek',
    org: 'DeepSeek',
    desc: 'Cost-efficient frontier model with exceptional math and coding capabilities.',
    tags: ['Language', 'Code', 'Open Source'],
    badge: 'open',
    rating: 4.7,
    reviews: 12045,
    price: '$0.14/1M tk',
    priceStart: 0.14,
    types: ['language', 'code', 'open'],
  },
  {
    id: 'mistral-large-3',
    icon: '💨',
    bg: '#FFF3E8',
    name: 'Mistral Large 3',
    lab: 'mistral',
    org: 'Mistral AI',
    desc: 'Top-tier reasoning with multilingual support and advanced function calling.',
    tags: ['Language', 'Code', 'Multilingual'],
    badge: null,
    rating: 4.5,
    reviews: 7432,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language', 'code'],
  },
  {
    id: 'grok-3',
    icon: '✖️',
    bg: '#F0F0F0',
    name: 'Grok 3 Beta',
    lab: 'xai',
    org: 'xAI',
    desc: 'Real-time internet access model. Excels at reasoning and data analysis tasks.',
    tags: ['Language', 'Reasoning', 'Code'],
    badge: null,
    rating: 4.5,
    reviews: 5432,
    price: '$3/1M tk',
    priceStart: 3,
    types: ['language'],
  },
  {
    id: 'phi-4',
    icon: '🪟',
    bg: '#EBF0FC',
    name: 'Phi-4',
    lab: 'microsoft',
    org: 'Microsoft',
    desc: 'Small but mighty. 14B parameters with strong reasoning-to-size ratio.',
    tags: ['Language', 'Reasoning', 'Efficient'],
    badge: null,
    rating: 4.4,
    reviews: 4123,
    price: '$0.07/1M tk',
    priceStart: 0.07,
    types: ['language'],
  },
  {
    id: 'qwen-2-5-72b',
    icon: '🌸',
    bg: '#FDEDF1',
    name: 'Qwen 2.5 72B',
    lab: 'qwen',
    org: 'Alibaba',
    desc: 'Alibaba open-source flagship with outstanding code and math capabilities.',
    tags: ['Language', 'Code', 'Open Source'],
    badge: 'open',
    rating: 4.6,
    reviews: 8543,
    price: '$0.40/1M tk',
    priceStart: 0.4,
    types: ['language', 'code', 'open'],
  },
  {
    id: 'command-r-plus',
    icon: '🔗',
    bg: '#E2F5EF',
    name: 'Command R+',
    lab: 'cohere',
    org: 'Cohere',
    desc: 'Enterprise RAG specialist with grounding, citations and tool use built-in.',
    tags: ['Language', 'Analysis', 'Multilingual'],
    badge: null,
    rating: 4.3,
    reviews: 3214,
    price: '$2.50/1M tk',
    priceStart: 2.5,
    types: ['language'],
  },
];
